In [20]:
%load_ext autoreload
# %autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [21]:
import logging
from sys import stdout
from datetime import datetime
import numpy as np
import os

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)

logging.info(f"{os.getlogin()}| {datetime.now()}")

[02-06 13:19:05][INFO] Vid| 2025-02-06 13:19:05.798093


In [22]:
import numpy as np
import logging
from sys import stdout
from datetime import datetime



def gauss_jordan(Ab: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante el método de Gauss-Jordan.
       Modificado para calcular la inversa.
    """
    if not isinstance(Ab, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        Ab = np.array(Ab, dtype=float)
    n = Ab.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote (con manejo de singularidad)
        p = None
        for pi in range(i, n):
            if Ab[pi, i] != 0:  # No es necesario el valor absoluto para la inversa
                p = pi
                break  # Salir del bucle tan pronto como se encuentra un pivote

        if p is None:
            raise np.linalg.LinAlgError("La matriz es singular (no tiene inversa).")  # Lanza una excepción específica de álgebra lineal

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            Ab[[i, p]] = Ab[[p, i]]  # Intercambio de filas más eficiente con NumPy

        # --- Eliminación: loop por fila (incluyendo la diagonal)
        pivot = Ab[i, i]  # Almacenar el pivote para la normalización
        Ab[i, :] = Ab[i, :] / pivot  # Normalizar la fila del pivote

        for j in range(n):
            if i == j:
                continue
            m = Ab[j, i]
            Ab[j, :] = Ab[j, :] - m * Ab[i, :]

        logging.info(f"\n{Ab}")

    return Ab[:, n:]  # Retorna la matriz identidad (la inversa)


def inv_matrix(A: np.ndarray) -> np.ndarray:
    """Calcula la inversa de una matriz cuadrada A usando Gauss-Jordan."""

    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)

    n = A.shape[0]
    if A.shape[0] != A.shape[1]:
        raise ValueError("La matriz debe ser cuadrada para calcular su inversa.")

    # Crear la matriz aumentada [A | I]
    I = np.eye(n)  # Matriz identidad
    Ab = np.hstack((A, I))

    try:
        inv_A = gauss_jordan(Ab)
        return inv_A
    except np.linalg.LinAlgError as e:
        logging.error(f"Error al calcular la inversa: {e}")
        return None  # o podrías lanzar la excepción nuevamente: raise
    except ValueError as e:  # Captura el error de "No existe solución única"
        logging.error(f"Error al calcular la inversa: {e}")
        return None


# Ejemplo de uso con la matriz A = [[2, -3], [-1, 1]]:
A = np.array([[2, -3], [-1, 1]], dtype=float)
inv_A = inv_matrix(A)

if inv_A is not None:
    print("Matriz original A:\n", A)
    print("Matriz inversa de A:\n", inv_A)

    # Comprobación (A * A_inv = I)
    I = np.dot(A, inv_A)
    print("A * A_inv:\n", I)
else:
    print("No se pudo calcular la inversa.")



    

[02-06 13:19:05][INFO] 
[[ 1.  -1.5  0.5  0. ]
 [ 0.  -0.5  0.5  1. ]]
[02-06 13:19:05][INFO] 
[[ 1.  0. -1. -3.]
 [-0.  1. -1. -2.]]
Matriz original A:
 [[ 2. -3.]
 [-1.  1.]]
Matriz inversa de A:
 [[-1. -3.]
 [-1. -2.]]
A * A_inv:
 [[1. 0.]
 [0. 1.]]


In [23]:
import numpy as np
import logging
from sys import stdout
from datetime import datetime



def gauss_jordan(Ab: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante el método de Gauss-Jordan.
       Modificado para calcular la inversa.
    """
    if not isinstance(Ab, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        Ab = np.array(Ab, dtype=float)
    n = Ab.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote (con manejo de singularidad)
        p = None
        for pi in range(i, n):
            if Ab[pi, i] != 0:  # No es necesario el valor absoluto para la inversa
                p = pi
                break  # Salir del bucle tan pronto como se encuentra un pivote

        if p is None:
            raise np.linalg.LinAlgError("La matriz es singular (no tiene inversa).")  # Lanza una excepción específica de álgebra lineal

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            Ab[[i, p]] = Ab[[p, i]]  # Intercambio de filas más eficiente con NumPy

        # --- Eliminación: loop por fila (incluyendo la diagonal)
        pivot = Ab[i, i]  # Almacenar el pivote para la normalización
        Ab[i, :] = Ab[i, :] / pivot  # Normalizar la fila del pivote

        for j in range(n):
            if i == j:
                continue
            m = Ab[j, i]
            Ab[j, :] = Ab[j, :] - m * Ab[i, :]

        logging.info(f"\n{Ab}")

    return Ab[:, n:]  # Retorna la matriz identidad (la inversa)


def inv_matrix(A: np.ndarray) -> np.ndarray:
    """Calcula la inversa de una matriz cuadrada A usando Gauss-Jordan."""

    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)

    n = A.shape[0]
    if A.shape[0] != A.shape[1]:
        raise ValueError("La matriz debe ser cuadrada para calcular su inversa.")

    # Crear la matriz aumentada [A | I]
    I = np.eye(n)  # Matriz identidad
    Ab = np.hstack((A, I))

    try:
        inv_A = gauss_jordan(Ab)
        return inv_A
    except np.linalg.LinAlgError as e:
        logging.error(f"Error al calcular la inversa: {e}")
        return None  # o podrías lanzar la excepción nuevamente: raise
    except ValueError as e:  # Captura el error de "No existe solución única"
        logging.error(f"Error al calcular la inversa: {e}")
        return None


# Ejemplo de uso con la matriz A = [[2, -3], [-1, 1]]:
B = np.array([
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0]
    ], dtype=float)
inv_B = inv_matrix(B)

if inv_B is not None:
    print("Matriz original B:\n", B)
    print("Matriz inversa de B:\n", inv_B)

    # Comprobación (A * A_inv = I)
    I = np.dot(B, inv_B)
    print("B * A_inv:\n", I)
else:
    print("No se pudo calcular la inversa.")

[02-06 13:19:05][INFO] 
[[ 1.    0.    0.    1.25  0.25  0.    0.    0.  ]
 [ 0.    0.    4.   -1.25 -0.25  1.    0.    0.  ]
 [ 0.    4.    1.   -0.75 -0.75  0.    1.    0.  ]
 [ 0.    3.    3.   -1.25 -0.25  0.    0.    1.  ]]
[02-06 13:19:05][INFO] 
[[ 1.      0.      0.      1.25    0.25    0.      0.      0.    ]
 [ 0.      1.      0.25   -0.1875 -0.1875  0.      0.25    0.    ]
 [ 0.      0.      4.     -1.25   -0.25    1.      0.      0.    ]
 [ 0.      0.      2.25   -0.6875  0.3125  0.     -0.75    1.    ]]
[02-06 13:19:05][INFO] 
[[ 1.        0.        0.        1.25      0.25      0.        0.
   0.      ]
 [ 0.        1.        0.       -0.109375 -0.171875 -0.0625    0.25
   0.      ]
 [ 0.        0.        1.       -0.3125   -0.0625    0.25      0.
   0.      ]
 [ 0.        0.        0.        0.015625  0.453125 -0.5625   -0.75
   1.      ]]
[02-06 13:19:05][INFO] 
[[  1.   0.   0.   0. -36.  45.  60. -80.]
 [  0.   1.   0.   0.   3.  -4.  -5.   7.]
 [  0.   0.   1.   0.  